image:
  file: gitpod.Dockerfile
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-python.python
    - juanblanco.solidity
    - NomicFoundation.hardhat-solidity
    - esbenp.prettier-vscode
    - ritwickdey.LiveServer


# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name : Install packages
    before: |
      npm install


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
